my_file = open('text1.txt', 'r', encoding = "utf-8")
content = my_file.read()
print(f'Содержимое файла: \n{content}')
my_file = open('text1.txt', 'r', encoding = "utf-8")
content = my_file.readlines()
print(f'Количество строк в файле - {len(content)}')
my_file = open('text1.txt', 'r', encoding = "utf-8")
content = my_file.readlines()
my_file = open('text1.txt', 'r', encoding = "utf-8")
for i in range(len(content)):
    print(f'Количество символов {i + 1} строки {len(content[i])}')
content = my_file.read()
content = content.split()
print(f'Общее количество слов - {len(content)}')
my_file.close()